// this code is autogenerated, do not check it into to your code repository

// ref lib/raylib.ex:10
const ray = @cImport({
  @cInclude("raylib.h");
});

pub const InitWindowOptions = struct { width: i32, height: i32, title: [*]const u8 };
const beam = @import("beam");

pub fn init_window(options: InitWindowOptions) beam.term {
ray.InitWindow(options.width, options.height, options.title);
return beam.make(.ok, .{});
}

pub fn close_window() beam.term {
ray.CloseWindow();
return beam.make(.ok, .{});
}
