// this code is autogenerated, do not check it into to your code repository

// ref lib/sdl.ex:6
const beam = @import("beam");

pub const InitFlags = struct { video: bool };

pub fn init(options: InitFlags) beam.term {
if (options.video) {}
return beam.make(.ok, .{});
}

pub fn quit() beam.term {
return beam.make(.ok, .{});
}
